- argopy/data_fetchers/erddap.py
- argopy/tests/test_fetchers.py
This is to fix and close https://github.com/euroargodev/argopy/issues/10
> Closes #10

- .travis.yml
- MANIFEST.in
- requirements-dev.txt
If the codebase passes this test the tarball is good to go!
> test tarball before a release

- docs/paper.md
This is part of the review at https://github.com/openjournals/joss-reviews/issues/2425
> Minor changes to the text of the JOSS paper

- argopy/data_fetchers/argovis_data.py
> Update argovis data source with correct API for region

- argopy/tests/test_xarray.py
- argopy/utilities.py
- argopy/xarray.py
Just a quick modification make the interpolation work on all variables.
> extend interpolation to all variables (expert mode)

- argopy/data_fetchers/localftp_data.py
xarray > 0.16.2 is raising an error for localftp open_mfdataset.
Removing the specification of the engine 'h5netcdf' seems to solve the pb.
> xarray > 0.16.2 raises error when opening local files

- argopy/tests/test_xarray.py
- argopy/xarray.py
- docs/data_manipulation.ipynb
- docs/whats-new.rst
> Teos sound_speed

- argopy/options.py
- argopy/utilities.py
> Fix bug in isAPIconnected

- argopy/fetchers.py
- argopy/plotters.py
- argopy/tests/test_fetchers_facade_data.py
- argopy/tests/test_fetchers_facade_index.py
- argopy/tests/test_plotters.py
- docs/api-hidden.rst
- docs/api.rst
- docs/data_quality_control.rst
- docs/whats-new.rst
A new API to insert the QC analysis report:
```python
from argopy.plotters import open_sat_altim_report
open_sat_altim_report(6902766)
open_sat_altim_report([6902766, 6902772, 6902914])
open_sat_altim_report([6902766, 6902772, 6902914], embed='dropdown')  # Default
open_sat_altim_report([6902766, 6902772, 6902914], embed='slide')
open_sat_altim_report([6902766, 6902772, 6902914], embed='list')
open_sat_altim_report([6902766, 6902772, 6902914], embed=None)
from argopy import DataFetcher
from argopy import IndexFetcher
DataFetcher().float([6902745, 6902746]).plot('qc_altimetry')
IndexFetcher().float([6902745, 6902746]).plot('qc_altimetry')
```
> Method to insert the CLS Satellite Altimeter Report figure on a notebook cell.

- CITATION.cff
- README.md
- docs/data_sources.rst
- docs/index.rst
- docs/install.rst
- docs/whats-new.rst
> Improve documentation

- argopy/data_fetchers/proto.py
- argopy/plot/dashboards.py
- argopy/tests/test_fetchers_data_gdac.py
- argopy/tests/test_fetchers_index_gdac.py
- argopy/tests/test_stores.py
- argopy/utilities.py
- ci/requirements/py3.7-dev.yml
- ci/requirements/py3.7-min.yml
- ci/requirements/py3.8-dev.yml
- ci/requirements/py3.8-min.yml
- docs/requirements.txt
- docs/whats-new.rst
- requirements.txt
- setup.py
Choose the release tag v0.X.Y, fill in the release title and click on the `Auto-generate release notes` button.  
This will trigger the [publish Github action](https://github.com/euroargodev/argopy/blob/master/.github/workflows/pythonpublish.yml) that will push the release on [Pypi](https://pypi.org/project/argopy/#history).
> Prepare for "v0.1.11 Rooster release 🐓" 

- argopy/data_fetchers/localftp_data.py
- argopy/data_fetchers/localftp_index.py
- ci/requirements/py3.7-all-pinned.yml
- ci/requirements/py3.8-all-pinned.yml
- docs/whats-new.rst
- setup.py
Choose the release tag v0.X.Y, fill in the release title and click on the `Auto-generate release notes` button.  
This will trigger the [publish Github action](https://github.com/euroargodev/argopy/blob/master/.github/workflows/pythonpublish.yml) that will push the release on [Pypi](https://pypi.org/project/argopy/#history).
> Prepare for "v0.1.12 Bee release 🐝 "

- argopy/utilities.py
- refactored fetch_status as a class
- fetch_status now uses html and no more shields io badges
- monitor_status can now handle to run outside of a notebook and still return a nice status
> Update API status monitor in utilities

- .github/workflows/pytests-upstream.yml
- .github/workflows/pytests.yml
Using mamba-org/setup-micromamba@v1 instead.
> provision-with-micromamba is deprecated

- argopy/data_fetchers/erddap_data.py
- argopy/data_fetchers/proto.py
- argopy/stores/filesystems.py
- argopy/utils/__init__.py
- argopy/utils/format.py
- argopy/utils/monitored_threadpool.py
- docs/api-hidden.rst
- new utils.format.UriCName to replace proto._cname
- parallel erddap request now keep track of chunk url/constraint definition
- fix bugs in httpstrore._open_mfdataset_from_erddap tracking of errors vs DataNotFound
Addresses #305
> Improve parallel erddap request logging

- argopy/data_fetchers/argovis_data.py
- argopy/data_fetchers/erddap_data.py
- argopy/data_fetchers/gdacftp_data.py
- docs/_static/pygments/lightbulb.css
- docs/index.rst
- docs/whats-new.rst
> Fix for failing to retrieve user name

- ci/requirements/py3.8-all-free.yml
- ci/requirements/py3.8-core-free.yml
- ci/requirements/py3.9-all-free.yml
- ci/requirements/py3.9-core-free.yml
- docs/install.rst
- setup.py
Choose a release tag v0.1.15, fill in the release title and click on the `Auto-generate release notes` button.  
This will trigger the [publish Github action](https://github.com/euroargodev/argopy/blob/master/.github/workflows/pythonpublish.yml) that will push the release on [Pypi](https://pypi.org/project/argopy/#history).
[![Publish on pypi](https://github.com/euroargodev/argopy/actions/workflows/pythonpublish.yml/badge.svg)](https://github.com/euroargodev/argopy/actions/workflows/pythonpublish.yml)
[![CI tests](https://github.com/euroargodev/argopy/actions/workflows/pytests.yml/badge.svg?branch=prepare-r0.1.15)](https://github.com/euroargodev/argopy/actions/workflows/pytests.yml) 
[![CI tests Upstream](https://github.com/euroargodev/argopy/actions/workflows/pytests-upstream.yml/badge.sv …
> Prepare 0.1.15 Baby chick release 🐥

- argopy/static/assets/admt_documentation_catalogue.json
Following Tanias email to ADMT mailing list:
Add the Argo pH Processing & QC Documents now available to the argopy ADMT docs submodule
> Add last 2 new ADMT documents

- argopy/tests/test_stores_fsspec.py
- ci/requirements/py3.8-all-free.yml
- ci/requirements/py3.8-core-free.yml
- ci/requirements/py3.9-all-free.yml
- ci/requirements/py3.9-core-free.yml
> Fix for fsspec > 2023.10.0

- README.md
- ci/envs_manager
- ci/requirements/py3.9-docs.yml
- docs/_static/pygments/coffee.css
- docs/energy.rst
- docs/index.rst
- docs/whats-new.rst
Let's give a try to [Green Metrics Tools](https://metrics.green-coding.io) from [Green Coding](https://www.green-coding.io/).
> Assess energy impact of argopy development activitites

- .github/workflows/pytests-upstream.yml
- .github/workflows/pytests.yml
Hey @gmaze ,
we have massively slimmed our Eco-CI tool and wanted to bring you the lastest update via PR.
- Using the newest super slim v4.0-rc3 version. Find all details like a 100x improvement here: https://github.com/green-coding-solutions/eco-ci-energy-estimation/releases/tag/v4.0-rc3 since we now pre-calcuate the power curves
- We now require `machine-uuid` to be set. I set again a secret as a pre-filled value. You will have to set `secrets.CARBONDB_MACHINE_UUID_PYTESTS_UPSTREAM` and `secrets.CARBONDB_MACHINE_UUID_PYTESTS` in your repo config. As usual: Just pick a random UUID
- I added the `send-data: true`, which was already by default before, but I thought it is nice to be explicit here
- CarbonDB integration requires only to be set on `start-measurement`. I removed the superflous …
> Eco-CI v4.0-rc3

- argopy/errors.py
- argopy/fetchers.py
- argopy/options.py
- argopy/tests/test_deprecated.py
- argopy/xarray.py
- docs/whats-new.rst
List of deprecations to raise:
⚠️  Must be coherent with changes in #389 !
> Introduces deprecation warnings before major v1.0.0 release

- argopy/data_fetchers/erddap_data_processors.py
- docs/whats-new.rst
> Fix issue 412, error when exporting a dataset to netcdf

- argopy/data_fetchers/argovis_data.py
- argopy/stores/float/implementations/argo_float_offline.py
- argopy/stores/float/implementations/argo_float_online.py
- argopy/stores/float/spec.py
- argopy/stores/implementations/http.py
- argopy/stores/implementations/local.py
- argopy/stores/index/implementations/index_s3.py
- argopy/tests/test_fetchers_dask_cluster.py
Add support for unexpected missing meta data from the fleetmonitoring API
this was missing from #439 
Address more concerns from #438
> Add ArgoIndex support for meta files index (part 2)

- argopy/data_fetchers/erddap_data.py
- argopy/data_fetchers/erddap_data_processors.py
- argopy/data_fetchers/erddap_refdata.py
- argopy/related/doi_snapshot.py
- argopy/stores/float/spec.py
- argopy/stores/implementations/http_erddap.py
- argopy/stores/kerchunker.py
Missing feature found when updating the documentation !
> Downloadable ArgoDOI file

- argopy/data_fetchers/erddap_data.py
- argopy/data_fetchers/erddap_data_processors.py
- argopy/data_fetchers/erddap_refdata.py
- argopy/related/doi_snapshot.py
- argopy/stores/float/spec.py
- argopy/stores/implementations/http_erddap.py
- argopy/stores/kerchunker.py
PR to complement #445 with bug fixes
> Fix bugs found during doc update 

- .github/workflows/tmp_debug.yml
- argopy/stores/spec.py
- argopy/tests/debug_windows.py
- argopy/tests/test_stores_fs_gdac.py
- argopy/utils/__init__.py
- argopy/utils/format.py
- ci/envs_manager
- ci/requirements/py3.12-all-pinned.yml
- ci/requirements/py3.12-core-pinned.yml
- docs/whats-new.rst
> Fix argo_split_path for Windows

- argopy/stores/index/implementations/pandas/index.py
- argopy/stores/index/implementations/pandas/search_engine.py
- argopy/stores/index/implementations/pyarrow/index.py
- argopy/stores/index/implementations/pyarrow/search_engine.py
- argopy/utils/checkers.py
- argopy/utils/geo.py
Additional work to close #494 
ping @ksato-aopc
Previous work from #495 :
- Fix utilities
- Fix the issue for the ArgoIndex
> Handle Data fetching with a regional selection going through the date line

- argopy/plot/plot.py
- argopy/plot/utils.py
Depending on the new longitude convention option value, some floats trajectory may not show up on a map.
PR to-do list:
> fix maps for new longitude convention option
